Repository YAXLib/YAXLib, pull requests merged in 2021-03, with the labels that each got.

#119 CI: Run also on Ubuntu on AppVeyor
  ReadMe.md
  appveyor.yml
Labels: build, size/M

#123 Added cross-framework compatibility
  YAXLib/ReflectionUtils.cs
  YAXLib/YAXLib.csproj
  YAXLibTests/ReflectionUtilsTest.cs
  YAXLibTests/SerializationTest.cs
  YAXLibTests/StringExtensionsForTest.cs
Labels: size/L

#124 Strip frameworks
  YAXLib/ReflectionUtils.cs
  YAXLib/YAXLib.csproj
  YAXLibTests/YAXLibTests.csproj
  appveyor.yml
Labels: size/S

#128 Normalize indent width csproj files
  .editorconfig
  YAXLib.sln
  YAXLib/YAXLib.csproj
  YAXLibTests/YAXLibTests.csproj
Labels: size/L

#127 Remove Microsoft.DotNet.PlatformAbstractions dependency for .NET Standard
  YAXLib/YAXLib.csproj
Labels: size/XS

#125 Create Package on AppVeyor
  Directory.Build.props
  YAXLib.sln
  YAXLib/YAXLib.csproj
  appveyor.yml
Labels: size/S

#129 Improved NuGet package
  YAXLib/YAXLib.csproj
Labels: size/XS

#133 Remove Hungarian notation
  YAXLib/Attributes/YAXSerializableTypeAttribute.cs
  YAXLib/EnumWrapper.cs
  YAXLib/KnownTypes/KnownTypes.cs
  YAXLib/MemberWrapper.cs
  YAXLib/TypeWrappersPool.cs
  YAXLib/UdtWrapper.cs
  YAXLib/YAXSerializer.cs
  YAXLibTests/SampleClasses/ColorExample.cs
  YAXLibTests/SampleClasses/FieldSerializationExample.cs
  YAXLibTests/SampleClasses/MoreComplexExample.cs
  YAXLibTests/SerializationTest.cs
Labels: code style, size/XL

#132 Deploy NuGet package from AppVeyor
  appveyor.yml
Labels: build, size/XS

#135 Typo in YAXSerializer.DimentionsAttributeName
  YAXLib/YAXSerializer.cs
  YAXLibTests/OverridingYAXLibMetadataTests.cs
Labels: breaking change, size/XS

#138 Remove GC.Collect
  YAXLib/TypeWrappersPool.cs
Labels: size/XS

#141 Correct readme.txt for Key file
  Key/Readme.txt
Labels: size/XS

#137 SerializerOptions for instanciating YAXSerializer
  YAXLib/Options/SerializerOptions.cs
  YAXLib/Options/YAXAttributeName.cs
  YAXLib/Options/YAXNameSpace.cs
  YAXLib/YAXSerializer.cs
  YAXLibTests/SerializerOptionsTests.cs
Labels: size/L
