Repository YAXLib/YAXLib, pull requests merged in 2022-05, with the labels that each got.

#170 Add generic constructor
  YAXLib/YAXSerializer.cs
  YAXLib/YAXSerializerOfT.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/SampleClasses/SimpleBookClass.cs
  YAXLibTests/SerializationTest.cs
Labels: size/L, breaking change

#178 Fix SonarCloud CI
  .github/workflows/SonarCloud.yml
Labels: size/XS

#180 Fix collection and dictionary serialization when publishing to single file
  YAXLib/ReflectionUtils.cs
Labels: size/S

#177 Implement option DontSerializeNullObjects for deserialization
  YAXLib/YAXSerializer.cs
  YAXLibTests/DeserializationTest.cs
  YAXLibTests/SampleClasses/SerializationOptionsSample.cs
Labels: size/L
