Repository YAXLib/YAXLib, pull requests merged in 2022-06, with the labels that each got.

#182 Trigger SonarCloud also for 'version/**' branches
  .github/workflows/SonarCloud.yml
Labels: size/XS

#185 Remove codecov integration and replace badges with SonarCloud badges
  ReadMe.md
  appveyor.yml
  codecov.yml
Labels: size/S

#187 Fix: SonarCloud do not support analysis of forked PRs
  .github/workflows/SonarCloud.yml
Labels: size/XS

#189 Remove usage of obsolete constructors and members
  DemoApplication/FormMain.Designer.cs
  DemoApplication/FormMain.cs
  DemoApplication/FormMain.resx
  YAXLibTests/DeserializationTest.cs
  YAXLibTests/ExceptionTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/KnownTypeTests.cs
  YAXLibTests/NamespaceTest.cs
  YAXLibTests/NumericMinMaxTests.cs
  YAXLibTests/OverridingYAXLibMetadataTests.cs
  YAXLibTests/SampleClasses/BookClassTestingSerializeAsValue.cs
  YAXLibTests/SampleClasses/CsprojParser.cs
  YAXLibTests/SampleClasses/Namespace/MutlilevelObjectsWithNamespaces.cs
  YAXLibTests/SampleClasses/SimpleBookClass.cs
  YAXLibTests/SampleClasses/SimpleBookClassWithDecimalPrice.cs
  YAXLibTests/SampleClasses/SimpleBookClassWithOrdering.cs
  YAXLibTests/SampleClasses/SimpleBookStruct.cs
  YAXLibTests/SerializationTest.cs
  YAXLibTests/SerializerOptionsTests.cs
Labels: size/XXL, refactoring
