Repository YAXLib/YAXLib, pull requests merged in 2022-07, with the labels that each got.

#190 Remove obsolete YAXLib classes and methods
  YAXLib/Exceptions/YAXElementValueAlreadyExistsException.cs
  YAXLib/Exceptions/YAXInvalidFormatProvided.cs
  YAXLib/MemberWrapper.cs
  YAXLib/TypeWrappersPool.cs
  YAXLib/UdtWrapper.cs
  YAXLib/YAXSerializer.cs
Labels: size/L, breaking change

#194 All (de)serialize tests for the generic and non-generic version
  YAXLib.sln.DotSettings
  YAXLib/IRecursionCounter.cs
  YAXLib/YAXSerializer.cs
  YAXLib/YAXSerializerOfT.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/GenericDeserializationTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/TestHelpers/GenericSerializerWrapper.cs
  YAXLibTests/TestHelpers/SerializerExtensions.cs
Labels: size/XL

#186 Improve maintainability: SonarCloud Cognitive Complexity <= 20
  .editorconfig
  YAXLib/Attributes/IYaxMemberLevelAttribute.cs
  YAXLib/Attributes/IYaxTypeLevelAttribute.cs
  YAXLib/Attributes/YAXAttributeForAttribute.cs
  YAXLib/Attributes/YAXAttributeForClassAttribute.cs
  YAXLib/Attributes/YAXBaseAttribute.cs
  YAXLib/Attributes/YAXCollectionAttribute.cs
  YAXLib/Attributes/YAXCollectionItemTypeAttribute.cs
  YAXLib/Attributes/YAXCommentAttribute.cs
  YAXLib/Attributes/YAXCustomSerializerAttribute.cs
  YAXLib/Attributes/YAXDictionaryAttribute.cs
  YAXLib/Attributes/YAXDontSerializeAttribute.cs
  YAXLib/Attributes/YAXDontSerializeIfNullAttribute.cs
  YAXLib/Attributes/YAXElementForAttribute.cs
  YAXLib/Attributes/YAXElementOrder.cs
  YAXLib/Attributes/YAXErrorIfMissedAttribute.cs
  YAXLib/Attributes/YAXFormatAttribute.cs
  YAXLib/Attributes/YAXNamespaceAttribute.cs
  YAXLib/Attributes/YAXNotCollectionAttribute.cs
  YAXLib/Attributes/YAXPreserveWhitespaceAttribute.cs
  YAXLib/Attributes/YAXSerializableFieldAttribute.cs
  YAXLib/Attributes/YAXSerializableTypeAttribute.cs
  YAXLib/Attributes/YAXSerializeAsAttribute.cs
  YAXLib/Attributes/YAXTypeAttribute.cs
  YAXLib/Attributes/YAXValueForAttribute.cs
  YAXLib/Attributes/YAXValueForClassAttribute.cs
  YAXLib/Deserialization.cs
  YAXLib/EnumWrapper.cs
  YAXLib/Exceptions/YAXDeserializationException.cs
  YAXLib/Helpers/CustomSerializerActivatorHelper.cs
  YAXLib/IRecursionCounter.cs
  YAXLib/MemberWrapper.cs
  YAXLib/ReflectionUtils.cs
  YAXLib/Serialization.cs
  YAXLib/StringUtils.cs
  YAXLib/UdtWrapper.cs
  YAXLib/YAXLib.csproj
  YAXLib/YAXSerializer.cs
  YAXLib/YAXSerializerOfT.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/ExceptionTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/StringUtilsTest.cs
  YAXLibTests/TestHelpers/GenericSerializerWrapper.cs
  YAXLibTests/TestHelpers/SerializerExtensions.cs
Labels: size/XXL

#192 Add option to serialize private members from base types
  YAXLib/Attributes/YAXSerializableTypeAttribute.cs
  YAXLib/Enums/YAXSerializationFields.cs
  YAXLib/Enums/YAXSerializationOptions.cs
  YAXLib/TypeExtensions.cs
  YAXLib/UdtWrapper.cs
  YAXLib/YAXSerializer.cs
  YAXLibTests/SampleClasses/ClassesWithBaseTypesSample.cs
  YAXLibTests/SerializationTestBase.cs
Labels: size/L

#199 Extend caching and use object pooling for better performance
  YAXLib/Attributes/YAXDictionaryAttribute.cs
  YAXLib/Caching/MemberWrapperCache.cs
  YAXLib/Caching/TypeCacheBase.cs
  YAXLib/Caching/TypeCacheStaticBase.cs
  YAXLib/Caching/UdtWrapperCache.cs
  YAXLib/Deserialization.cs
  YAXLib/EnumWrapper.cs
  YAXLib/MemberWrapper.cs
  YAXLib/Options/SerializerOptions.cs
  YAXLib/Pooling/ObjectPools/IObjectPool.cs
  YAXLib/Pooling/ObjectPools/IPoolCounters.cs
  YAXLib/Pooling/ObjectPools/ObjectPool.cs
  YAXLib/Pooling/ObjectPools/ObjectPoolConcurrent.cs
  YAXLib/Pooling/ObjectPools/PoolPolicy.cs
  YAXLib/Pooling/ObjectPools/PooledObject.cs
  YAXLib/Pooling/PoolRegistry.cs
  YAXLib/Pooling/PoolSettings.cs
  YAXLib/Pooling/PoolingException.cs
  YAXLib/Pooling/SpecializedPools/CollectionPool.cs
  YAXLib/Pooling/SpecializedPools/DictionaryPool.cs
  YAXLib/Pooling/SpecializedPools/HashSetPool.cs
  YAXLib/Pooling/SpecializedPools/ListPool.cs
  YAXLib/Pooling/SpecializedPools/SpecializedPoolBase.cs
  YAXLib/Pooling/SpecializedPools/StringBuilderPool.cs
  YAXLib/Pooling/YAXLibPools/PoolBase.cs
  YAXLib/Pooling/YAXLibPools/SerializerPool.cs
  YAXLib/ReflectionUtils.cs
  YAXLib/Serialization.cs
  YAXLib/StringUtils.cs
  YAXLib/TypeWrappersPool.cs
  YAXLib/XmlNamespaceManager.cs
  YAXLib/YAXLib.csproj
  YAXLib/YAXParsingErrors.cs
  YAXLib/YAXSerializer.cs
  YAXLibTests/Caching/MemberWrapperCacheTests.cs
  YAXLibTests/Caching/UdtWrapperCacheTests.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/GeneralToString.cs
  YAXLibTests/GenericDeserializationTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/Pooling/CollectionPoolTests.cs
  YAXLibTests/Pooling/ConcurrentPoolingTests.cs
  YAXLibTests/Pooling/DictionaryPoolTests.cs
  YAXLibTests/Pooling/HashSetPoolTests.cs
  YAXLibTests/Pooling/ListPoolTests.cs
  YAXLibTests/Pooling/ObjectPoolClassesTests.cs
  YAXLibTests/Pooling/PoolBalanceTests.cs
  YAXLibTests/Pooling/PoolPolicyTests.cs
  YAXLibTests/Pooling/SerializerPoolTests.cs
  YAXLibTests/Pooling/StringBuilderPoolTests.cs
  YAXLibTests/SampleClasses/ClassesWithBaseTypesSample.cs
  YAXLibTests/SampleClasses/Code4PublicTheme.cs
  YAXLibTests/SampleClasses/SelfReferencingObjects/CalculatedPropertiesCanCauseInfiniteLoop.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/TestHelpers/PoolingHelpers.cs
  YAXLibTests/TestSetup.cs
  YAXLibTests/YAXLibTests.csproj
Labels: performance, size/XXL, breaking change

#200 Move methods from YAXSerializer to UdtWrapper
  YAXLib/Caching/UdtWrapperCache.cs
  YAXLib/Deserialization.cs
  YAXLib/Serialization.cs
  YAXLib/UdtWrapper.cs
  YAXLib/YAXSerializer.cs
Labels: size/L, refactoring
