Repository YAXLib/YAXLib, pull requests merged in 2023-07, with the labels that each got.

#227 Feature/yaxlib visual studio debugger friendly
  YAXLib/Attributes/YAXTextEmbeddingAttribute.cs
  YAXLib/Caching/CacheBase.cs
  YAXLib/Caching/CacheStaticBase.cs
  YAXLib/Caching/MemberWrapperCache.cs
  YAXLib/Caching/UdtWrapperCache.cs
  YAXLib/Customization/IMemberContext.cs
  YAXLib/Customization/Locker.cs
  YAXLib/Customization/MemberContext.cs
  YAXLib/DefaultTypeInspector.cs
  YAXLib/Deserialization.cs
  YAXLib/Enums/YAXSerializationOptions.cs
  YAXLib/FieldWrapper.cs
  YAXLib/IMemberDescriptor.cs
  YAXLib/ITypeInspector.cs
  YAXLib/KnownTypes/ExceptionKnownBaseType.cs
  YAXLib/MemberWrapper.cs
  YAXLib/Options/SerializerOptions.cs
  YAXLib/Pooling/PoolRegistry.cs
  YAXLib/Pooling/SpecializedPools/CollectionPool.cs
  YAXLib/Pooling/SpecializedPools/DictionaryPool.cs
  YAXLib/Pooling/SpecializedPools/HashSetPool.cs
  YAXLib/Pooling/SpecializedPools/ListPool.cs
  YAXLib/Pooling/SpecializedPools/SpecializedPoolBase.cs
  YAXLib/Pooling/SpecializedPools/StringBuilderPool.cs
  YAXLib/Pooling/YAXLibPools/SerializerPool.cs
  YAXLib/PropertyWrapper.cs
  YAXLib/ReflectionExtensions.cs
  YAXLib/ReflectionUtils.cs
  YAXLib/Serialization.cs
  YAXLib/UdtWrapper.cs
  YAXLibTests/Caching/MemberWrapperCacheTests.cs
  YAXLibTests/Caching/UdtWrapperCacheTests.cs
  YAXLibTests/CustomTypeInspectorTests.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/SampleClasses/SerializationOptionsSample.cs
  YAXLibTests/SerializationContextTests.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/TestHelpers/PoolingHelpers.cs
  YAXLibTests/YAXLibTests.csproj
Labels: size/XXL, breaking change

#228 Fix: Possible null reference return
  YAXLib/FieldWrapper.cs
  YAXLib/PropertyWrapper.cs
Labels: size/XS

#229 Replace preprocessor directive "NET6_0" with "NET"
  YAXLib/MemberWrapper.cs
  YAXLib/ReflectionUtils.cs
  YAXLib/StringExtensions.cs
  YAXLib/StringUtils.cs
Labels: size/S

#230 Set SerializerOptions.TypeInspector to DefaultTypeInspector.Instance when instantiating
  YAXLib/ITypeInspector.cs
  YAXLib/Options/SerializerOptions.cs
  YAXLib/UdtWrapper.cs
Labels: size/S

#232 Replace sonar.login with sonar.token for CI
  .github/workflows/SonarCloud.yml
Labels: size/XS
