Repository YAXLib/YAXLib, pull requests merged in 2023-08, with the labels that each got.

#235 Update github actions: setup-java, checkout, cache
  .github/workflows/SonarCloud.yml
Labels: size/S

#236 Fix/get default value type
  YAXLib/ReflectionUtils.cs
  YAXLibTests/ReflectionUtilsTest.cs
Labels: size/M

#237 Prepare for v4.2
  .github/workflows/SonarCloud.yml
  YAXLib/Attributes/YAXTextEmbeddingAttribute.cs
  YAXLib/Caching/CacheBase.cs
  YAXLib/Caching/CacheStaticBase.cs
  YAXLib/Caching/MemberWrapperCache.cs
  YAXLib/Caching/UdtWrapperCache.cs
  YAXLib/Customization/IMemberContext.cs
  YAXLib/Customization/Locker.cs
  YAXLib/Customization/MemberContext.cs
  YAXLib/DefaultTypeInspector.cs
  YAXLib/Deserialization.cs
  YAXLib/Enums/YAXSerializationOptions.cs
  YAXLib/FieldWrapper.cs
  YAXLib/IMemberDescriptor.cs
  YAXLib/ITypeInspector.cs
  YAXLib/KnownTypes/ExceptionKnownBaseType.cs
  YAXLib/MemberWrapper.cs
  YAXLib/Options/SerializerOptions.cs
  YAXLib/Pooling/PoolRegistry.cs
  YAXLib/Pooling/SpecializedPools/CollectionPool.cs
  YAXLib/Pooling/SpecializedPools/DictionaryPool.cs
  YAXLib/Pooling/SpecializedPools/HashSetPool.cs
  YAXLib/Pooling/SpecializedPools/ListPool.cs
  YAXLib/Pooling/SpecializedPools/SpecializedPoolBase.cs
  YAXLib/Pooling/SpecializedPools/StringBuilderPool.cs
  YAXLib/Pooling/YAXLibPools/SerializerPool.cs
  YAXLib/PropertyWrapper.cs
  YAXLib/ReflectionExtensions.cs
  YAXLib/ReflectionUtils.cs
  YAXLib/Serialization.cs
  YAXLib/StringExtensions.cs
  YAXLib/StringUtils.cs
  YAXLib/UdtWrapper.cs
  YAXLibTests/Caching/MemberWrapperCacheTests.cs
  YAXLibTests/Caching/UdtWrapperCacheTests.cs
  YAXLibTests/CustomTypeInspectorTests.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/ReflectionUtilsTest.cs
  YAXLibTests/SampleClasses/SerializationOptionsSample.cs
  YAXLibTests/SerializationContextTests.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/TestHelpers/PoolingHelpers.cs
  YAXLibTests/YAXLibTests.csproj
Labels: enhancement, size/XXL

#238 Implement C# 11 Raw String Interpolation for YAXLibTests
  YAXLibTests/CustomSerializerTests.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/ExceptionTests.cs
  YAXLibTests/GenericDeserializationTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/KnownTypeTests.cs
  YAXLibTests/NamespaceTest.cs
  YAXLibTests/OverridingYAXLibMetadataTests.cs
  YAXLibTests/Pooling/ConcurrentPoolingTests.cs
  YAXLibTests/Pooling/PoolBalanceTests.cs
  YAXLibTests/SampleClasses/CollectionOfInterfacesSample.cs
  YAXLibTests/SampleClasses/GenericCollectionsSample.cs
  YAXLibTests/SampleClasses/InterfaceMatchingSample.cs
  YAXLibTests/SampleClasses/MoreComplexBook.cs
  YAXLibTests/SampleClasses/MoreComplexBook2.cs
  YAXLibTests/SampleClasses/MoreComplexBook3.cs
  YAXLibTests/SampleClasses/MoreComplexExample.cs
  YAXLibTests/SampleClasses/MultiDimArraySample.cs
  YAXLibTests/SampleClasses/MultilevelClass.cs
  YAXLibTests/SampleClasses/MultipleCommentsTest.cs
  YAXLibTests/SampleClasses/NestedDicSample.cs
  YAXLibTests/SampleClasses/PathsExample.cs
  YAXLibTests/SampleClasses/SerializationOptionsSample.cs
  YAXLibTests/SampleClasses/TextEmbedding/DisallowedAttributeCombinationSample.cs
  YAXLibTests/SampleClasses/TextEmbedding/SuccessfulEmbeddingSample.cs
  YAXLibTests/SampleClasses/WarehouseWithDictionaryNoContainer.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/StringExtensionsForTest.cs
  YAXLibTests/TestHelpers/PoolingHelpers.cs
Labels: size/XXL

#239 Bump version to v4.2.0
  appveyor.yml
Labels: size/XS
