Repository YAXLib/YAXLib, pull requests merged in 2024-07, with the labels that each got.

#251 Fix serialize to IEnumerable T without runtime type
  YAXLib/Deserialization.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/SampleClasses/IEnumerableHolderClass.cs
Labels: enhancement, size/L

#252 chore: Refactor unit tests
  YAXLib/Deserialization.cs
  YAXLibTests/Caching/MemberWrapperCacheTests.cs
  YAXLibTests/Caching/UdtWrapperCacheTests.cs
  YAXLibTests/CustomSerializerTests.cs
  YAXLibTests/DeserializationTestBase.cs
  YAXLibTests/ExceptionTests.cs
  YAXLibTests/GenericDeserializationTests.cs
  YAXLibTests/GenericSerializationTests.cs
  YAXLibTests/KnownTypeTests.cs
  YAXLibTests/NamespaceTest.cs
  YAXLibTests/OverridingYAXLibMetadataTests.cs
  YAXLibTests/Pooling/CollectionPoolTests.cs
  YAXLibTests/Pooling/ConcurrentPoolingTests.cs
  YAXLibTests/Pooling/DictionaryPoolTests.cs
  YAXLibTests/Pooling/HashSetPoolTests.cs
  YAXLibTests/Pooling/ListPoolTests.cs
  YAXLibTests/Pooling/ObjectPoolClassesTests.cs
  YAXLibTests/Pooling/PoolBalanceTests.cs
  YAXLibTests/Pooling/SerializerPoolTests.cs
  YAXLibTests/Pooling/StringBuilderPoolTests.cs
  YAXLibTests/ReflectionUtilsTest.cs
  YAXLibTests/SerializationContextTests.cs
  YAXLibTests/SerializationTestBase.cs
  YAXLibTests/StringUtilsTest.cs
  YAXLibTests/XMLUtilsTest.cs
Labels: size/XXL, code style

#253 chore: Resolve SonarCloud code issues
  DemoApplication/FormMain.Designer.cs
  DemoApplication/FormMain.cs
  DemoApplication/FormMain.resx
  YAXLib/Attributes/YAXCommentAttribute.cs
  YAXLib/Deserialization.cs
  YAXLib/EnumWrapper.cs
  YAXLib/KnownTypes/TimeSpanKnownType.cs
  YAXLib/StringUtils.cs
  YAXLib/XMLUtils.cs
  YAXLib/YAXLib.csproj
  YAXLibTests/SampleClasses/IEnumerableHolderClass.cs
  appveyor.yml
Labels: size/L, code style
